version: '3.9'
services:
  one_media_db:
    container_name: one_media_db
    restart: always
    image: 'postgres:13'
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./database/volume:/var/lib/postgresql/data:rw
      - ./database/init_scripts:/docker-entrypoint-initdb.d

  base_python_image:
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/base_python_image/Dockerfile
    image: base_python:v1

  base_java_image:
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/base_java_image/Dockerfile
    image: base_java:v1

  one_media_tlg_extractor:
    container_name: one_media_tlg_extractor
    depends_on:
      - one_media_db
      - base_python_image
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/tlg/extractor/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./tlg/extractor/volume/logs:/OneMedia/APPS/tlg/extractor/logs:rw
      - ./tlg/extractor/volume/sessions:/OneMedia/APPS/tlg/extractor/sessions:rw
    links:
      - "one_media_db:database"

  one_media_web_crawler:
    container_name: one_media_web_crawler
    restart: always
    depends_on:
      - one_media_db
      - base_python_image
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/web_crawler/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./web_crawler/volume/logs:/OneMedia/APPS/web_crawler/crawlers/logs:rw
    links:
      - "one_media_db:database"

  one_media_vk_extractor:
    container_name: one_media_vk_extractor
    depends_on:
      - one_media_db
      - base_python_image
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/vk/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./vk/volume/logs:/OneMedia/APPS/vk/logs:rw
      - ./vk/volume/sessions:/OneMedia/APPS/vk/sessions:rw
    links:
      - "one_media_db:database"

  one_media_tlg_bot:
    container_name: one_media_tlg_bot
    # restart: always
    depends_on:
      - one_media_db
      - base_python_image
      - one_media_search
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/tlg/bot/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./tlg/bot/volume/logs:/OneMedia/APPS/tlg/bot/logs:rw
      - ./tlg/bot/volume/sessions:/OneMedia/APPS/tlg/bot/sessions:rw
    links:
      - "one_media_db:database"
      - "one_media_search:search"

  one_media_tlg_monitoring_bot:
    container_name: one_media_tlg_monitoring_bot
    # restart: always
    depends_on:
      - one_media_db
      - base_python_image
      - one_media_search
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/tlg/monitoring_bot/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./tlg/monitoring_bot/volume/logs:/OneMedia/APPS/tlg/monitoring_bot/logs:rw
      - ./database/backup:/OneMedia/APPS/tlg/monitoring_bot/db_backup:rw
    links:
      - "one_media_db:database"
      - "one_media_search:search"

  one_media_tlg_subscribers:
    container_name: one_media_tlg_subscribers
    # restart: always
    depends_on:
      - one_media_db
      - base_python_image
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/tlg/subscribers/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./tlg/subscribers/volume/logs:/OneMedia/APPS/tlg/subscribers/logs:rw
    links:
      - "one_media_db:database"

  one_media_search:
    container_name: one_media_search
    depends_on:
      - one_media_db
      - base_java_image
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8083:8083"
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/search/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./search/volume/logs:/OneMedia/BUILD_DEPLOY/search/logs:rw
      - ./search/volume/index:/OneMedia/BUILD_DEPLOY/search/index:rw
    links:
      - "one_media_db:database"

  one_media_ui:
    container_name: one_media_ui
    depends_on:
      - one_media_db
      - one_media_search
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "80:8080"
    build:
      context: ../
      dockerfile: BUILD_DEPLOY/ui/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./ui/volume/logs:/OneMedia/BUILD_DEPLOY/ui/logs:rw
    links:
      - "one_media_db:database"
      - "one_media_search"

  grafana:
    container_name: grafana
    build:
      context: grafana/
    depends_on:
      - one_media_db
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./grafana/volume:/var/lib/grafana
    links:
      - "one_media_db:database"
